name: Build KernelSU Module

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整历史以计算 commit-count

      - name: Set up Git User
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Web Production
        run: npm run build # 强行先生成 dist/ 目录

      - name: Package Module
        run: npm run package # 再执行打包逻辑

      - name: Upload Zip Artifact
        uses: actions/upload-artifact@v4
        with:
          name: joyose-edit-release
          path: release/*.zip
